version: '3'
services:
    retro:
        image: retropie-games
        build:
            context: .
            dockerfile: Dockerfile
        environment:
            - RETROPIEVERSION=4.1
            - IMAGE_SIZE_IN_GB=25
        privileged: true
        volumes:
            - ./roms:/workspace/roms
            - ./BIOS:/workspace/BIOS
            - ./images:/workspace/images
            - ./scripts:/workspace/scripts
